using Microsoft.Build.Framework;
using Microsoft.Data.SqlClient;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;
using static System.Net.Mime.MediaTypeNames;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace project.Models
{
    public class login1
    {
        SqlConnection con = new SqlConnection(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Rentify_DB;Integrated Security=True;Connect Timeout=30;Encrypt=False;");
        public int Id { get; set; }
   
        public string Uname { get; set; }
        public string Passwrd { get; set; }
        ////Retrieve all records from a table
        public List<login1> getData()
        {
            List<login1> lstEmp = new List<login1>();
            SqlDataAdapter apt = new SqlDataAdapter("select * from logindata", con);
            DataSet ds = new DataSet();
            apt.Fill(ds);
            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                lstEmp.Add(new login1
                {
                    Id = Convert.ToInt32(dr["Id"].ToString()),
                    Uname = dr["Uname"].ToString(),
                    Passwrd = dr["Passwrd"].ToString(),

                });
            }
            return lstEmp;
        }

        public login1 getData(string Id)
        {
            login1 emp1 = new login1();
            SqlCommand cmd = new SqlCommand("select * from logindata where id='" + Id +
           "'", con);

            con.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    emp1.Id = Convert.ToInt32(dr["Id"].ToString());
                    emp1.Uname = dr["Uname"].ToString();
                    emp1.Passwrd = dr["Passwrd"].ToString();

                }
            }
            con.Close();
            return emp1;
        }

        public bool insert(login1 Emp)
        {
            // Assuming "Id" is auto-generated by the database, if not, you need to add it as a parameter.
            string query = "INSERT INTO logindata (Uname, Passwrd) VALUES (@Uname, @Passwrd)";

            // Use "using" statement for automatic disposal of SqlConnection
            using (SqlConnection con = new SqlConnection(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Rentify_DB;Integrated Security=True;Connect Timeout=30;Encrypt=False;"))
            {
                // Use "using" statement for SqlCommand to ensure it's disposed properly
                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    cmd.Parameters.AddWithValue("@Uname", Emp.Uname);
                    cmd.Parameters.AddWithValue("@Passwrd", Emp.Passwrd);

                    con.Open(); // Open connection
                    int i = cmd.ExecuteNonQuery(); // Execute the non-query command
                    con.Close(); // Close connection explicitly here because of the return statement below (though using will ensure closure)

                    return i >= 1;
                }
            }
            //public List<login1> getData()
            //{
            //	List<login1> lstEmp = new List<login1>();
            //	SqlDataAdapter apt = new SqlDataAdapter("select * from logindetails", con);
            //	DataSet ds = new DataSet();
            //	apt.Fill(ds);
            //	foreach (DataRow dr in ds.Tables[0].Rows)
            //	{
            //		lstEmp.Add(new login1
            //		{
            //			Id = Convert.ToInt32(dr["Id"].ToString()),
            //			Uname = dr["Name"].ToString(),
            //			Passwrd = dr["Dept"].ToString(),
            //		});
            //	}
            //	return lstEmp;
            //}
            //Retrieve single record from a table

            //public login1 getData(string Id)
            //{
            //	login1 emp = new login1();
            //	SqlCommand cmd = new SqlCommand("select * from tbl_emp where id='" + Id +
            //	"'", con);
            //	con.Open();
            //	SqlDataReader dr = cmd.ExecuteReader();
            //	if (dr.HasRows)
            //	{
            //		while (dr.Read())
            //		{
            //			emp.Id = Convert.ToInt32(dr["Id"].ToString());
            //			emp.Uname = dr["Uname"].ToString();
            //			emp.Passwrd = dr["Passwrd"].ToString();
            //		}
            //	}
            //	con.Close();
            //	return emp;
            //}
            //Insert a record into a database table
            //public bool insert(login1 Emp)
            //{
            ////	SqlCommand cmd = new SqlCommand("INSERT INTO logindata (Uname, Passwrd) VALUES (@Uname, @Passwrd)", con);
            //	cmd.Parameters.AddWithValue("@Uname", Emp.Uname);
            //	cmd.Parameters.AddWithValue("@Passwrd", Emp.Passwrd);
            //con.Open();
            //int i = cmd.ExecuteNonQuery();
            //con.Close();
            //return i >= 1;
            //}

            //public bool insert(login1 Emp)
            //{
            //	SqlCommand cmd = new SqlCommand("insert into logindetails values(@Uname, Passwrd)", con);
            //	cmd.Parameters.AddWithValue("@Uname", Emp.Uname);
            //	cmd.Parameters.AddWithValue("@Passwrd", Emp.Passwrd);
            //	con.Open();
            //	int i = cmd.ExecuteNonQuery();
            //	if (i >= 1)
            //	{
            //		return true;
            //	}
            //	return false;
            //}
        }
    }
}
		//Update a record into a database table
		//public bool update(EmployeeModel Emp)
		//{
		//	SqlCommand cmd = new SqlCommand("update tbl_emp set Name=@name,
		//	Dept = @dept, Salary = @salary where Id = @id", con);
		//	cmd.Parameters.AddWithValue("@name", Emp.Name);
		//	cmd.Parameters.AddWithValue("@dept", Emp.Department);
		//	cmd.Parameters.AddWithValue("@salary", Emp.Salary);
		//	cmd.Parameters.AddWithValue("@id", Emp.Id);
		//	con.Open();
		//	int i = cmd.ExecuteNonQuery();
		//	if (i >= 1)
		//	{
		//		return true;
		//	}
		//	return false;
		//}


//		SqlConnection con = new SqlConnection(@"Data Source = (localdb)\MSSQLLocalDB;Initial Catalog = Rentify_DB; Integrated Security = True; Connect Timeout = 30; Encrypt=False;");
//        public int Id { get; set; }

//        [Required(ErrorMessage = "Please enter Username")]
//        public string Uname { get; set; }
//        [Required(ErrorMessage = "Please enter Password")]

//        public string Passwrd { get; set; }

//        public List<login1> getData()
//        {
//            List<login1> lstEmp = new List<login1>();
//            SqlDataAdapter apt = new SqlDataAdapter("select * from dbo.logindata", con);
//            DataSet ds = new DataSet();
//            apt.Fill(ds);
//            foreach (DataRow dr in ds.Tables[0].Rows)
//            {
//                lstEmp.Add(new login1
//                {
//                    Id = Convert.ToInt32(dr["Id"].ToString()),
//                    Uname = dr["Uname"].ToString(),
//                    Passwrd = dr["Passwrd"].ToString(),

//                });
//            }
//            return lstEmp;

//        }

//        public bool insert(login1 Emp)
//        {
//            SqlCommand cmd = new SqlCommand("insert into dbo.logindata values(@Uname, @Passwrd)", con);

//            cmd.Parameters.AddWithValue("@Uname", Emp.Uname);
//            cmd.Parameters.AddWithValue("@Passwrd", Emp.Passwrd);
//            con.Open();
//            int i = cmd.ExecuteNonQuery();
//            if (i >= 1)
//            {
//                return true;
//            }
//            return false;
//        }
//    }
//}
